Failed test,Arch,Error message,Track,status,assignee
inductor.test_torchinductor::GPUTests::test_convolution1_cuda,gfx942,"{'message': 'AssertionError: Tensor-likes are not close!\n\nMismatched elements: 4 / 2352 (0.2%)\nGreatest absolute difference: 0.000102996826171875 at index (1, 4, 0, 7) (up to 6e-05 allowed)\nGreatest relative difference: 0.247314453125 at index (0, 4, 11, 9) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution1_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11304, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 3998, in test_convolution1\n    self.common(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 622, in check_model_gpu\n    check_model(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 478, in check_model\n    self.assertEqual(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py"", line 3858, in assertEqual\n    raise error_metas.pop()[0].to_error(\nAssertionError: Tensor-likes are not close!\n\nMismatched elements: 4 / 2352 (0.2%)\nGreatest absolute difference: 0.000102996826171875 at index (1, 4, 0, 7) (up to 6e-05 allowed)\nGreatest relative difference: 0.247314453125 at index (0, 4, 11, 9) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution1_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::GPUTests::test_convolution3_cuda,gfx942,"{'message': 'AssertionError: Tensor-likes are not close!\n\nMismatched elements: 4 / 2352 (0.2%)\nGreatest absolute difference: 0.000102996826171875 at index (1, 4, 0, 7) (up to 6e-05 allowed)\nGreatest relative difference: 0.247314453125 at index (0, 4, 11, 9) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution1_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11304, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 3998, in test_convolution1\n    self.common(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 622, in check_model_gpu\n    check_model(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 478, in check_model\n    self.assertEqual(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py"", line 3858, in assertEqual\n    raise error_metas.pop()[0].to_error(\nAssertionError: Tensor-likes are not close!\n\nMismatched elements: 4 / 2352 (0.2%)\nGreatest absolute difference: 0.000102996826171875 at index (1, 4, 0, 7) (up to 6e-05 allowed)\nGreatest relative difference: 0.247314453125 at index (0, 4, 11, 9) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution1_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestABICompatibleCpu::test_reuse_kernel_dynamic_abi_compatible_cpu,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCpu.test_reuse_kernel_dynamic_abi_compatible_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 1647, in test_reuse_kernel_dynamic\n    self.check_model(m, example_inputs, dynamic_shapes=dynamic_shapes)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 116, in check_model\n    actual = AOTIRunnerUtil.run(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 117, in run\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1714, in codegen_with_cpp_wrapper\n    return self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 4115, in codegen_node\n    cpp_kernel_proxy.codegen_nodes(nodes)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3606, in codegen_nodes\n    self.codegen_functions(fn_list, var_sizes_list, vec_dtype)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3416, in codegen_functions\n    scalar_kernel = codegen_kernel(CppKernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3393, in codegen_kernel\n    run(kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3405, in run\n    fn(vars, reduction_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3590, in fn\n    return node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCpu.test_reuse_kernel_dynamic_abi_compatible_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestABICompatibleCpuWithStackAllocation::test_reuse_kernel_dynamic_abi_compatible_cpu_with_stack_allocation,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCpuWithStackAllocation.test_reuse_kernel_dynamic_abi_compatible_cpu_with_stack_allocation\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 1647, in test_reuse_kernel_dynamic\n    self.check_model(m, example_inputs, dynamic_shapes=dynamic_shapes)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 116, in check_model\n    actual = AOTIRunnerUtil.run(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 117, in run\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1714, in codegen_with_cpp_wrapper\n    return self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 4115, in codegen_node\n    cpp_kernel_proxy.codegen_nodes(nodes)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3606, in codegen_nodes\n    self.codegen_functions(fn_list, var_sizes_list, vec_dtype)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3416, in codegen_functions\n    scalar_kernel = codegen_kernel(CppKernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3393, in codegen_kernel\n    run(kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3405, in run\n    fn(vars, reduction_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3590, in fn\n    return node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCpuWithStackAllocation.test_reuse_kernel_dynamic_abi_compatible_cpu_with_stack_allocation\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestABICompatibleCuda::test_foreach_multiple_dynamic_abi_compatible_cuda,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCuda.test_foreach_multiple_dynamic_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 943, in test_foreach_multiple_dynamic\n    self.check_model_with_multiple_inputs(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 148, in check_model_with_multiple_inputs\n    list_actual = AOTIRunnerUtil.run_multiple(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 135, in run_multiple\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1628, in codegen_with_cpp_wrapper\n    compiled = self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py"", line 80, in codegen_node\n    return self._triton_scheduling.codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1174, in codegen_node\n    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1380, in codegen_node_schedule\n    self.codegen_node_schedule_with_kernel(node_schedule, kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1488, in codegen_node_schedule_with_kernel\n    node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCuda.test_foreach_multiple_dynamic_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestABICompatibleCuda::test_reuse_kernel_dynamic_abi_compatible_cuda,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCuda.test_reuse_kernel_dynamic_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 1647, in test_reuse_kernel_dynamic\n    self.check_model(m, example_inputs, dynamic_shapes=dynamic_shapes)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 116, in check_model\n    actual = AOTIRunnerUtil.run(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 117, in run\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1628, in codegen_with_cpp_wrapper\n    compiled = self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py"", line 80, in codegen_node\n    return self._triton_scheduling.codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1174, in codegen_node\n    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1380, in codegen_node_schedule\n    self.codegen_node_schedule_with_kernel(node_schedule, kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1488, in codegen_node_schedule_with_kernel\n    node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestABICompatibleCuda.test_reuse_kernel_dynamic_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestNonABICompatibleCpu::test_reuse_kernel_dynamic_non_abi_compatible_cpu,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCpu.test_reuse_kernel_dynamic_non_abi_compatible_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 1647, in test_reuse_kernel_dynamic\n    self.check_model(m, example_inputs, dynamic_shapes=dynamic_shapes)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 116, in check_model\n    actual = AOTIRunnerUtil.run(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 117, in run\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1714, in codegen_with_cpp_wrapper\n    return self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 4115, in codegen_node\n    cpp_kernel_proxy.codegen_nodes(nodes)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3606, in codegen_nodes\n    self.codegen_functions(fn_list, var_sizes_list, vec_dtype)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3416, in codegen_functions\n    scalar_kernel = codegen_kernel(CppKernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3393, in codegen_kernel\n    run(kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3405, in run\n    fn(vars, reduction_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3590, in fn\n    return node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCpu.test_reuse_kernel_dynamic_non_abi_compatible_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestNonABICompatibleCuda::test_foreach_multiple_dynamic_non_abi_compatible_cuda,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCuda.test_foreach_multiple_dynamic_non_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 943, in test_foreach_multiple_dynamic\n    self.check_model_with_multiple_inputs(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 148, in check_model_with_multiple_inputs\n    list_actual = AOTIRunnerUtil.run_multiple(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 135, in run_multiple\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1628, in codegen_with_cpp_wrapper\n    compiled = self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py"", line 80, in codegen_node\n    return self._triton_scheduling.codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1174, in codegen_node\n    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1380, in codegen_node_schedule\n    self.codegen_node_schedule_with_kernel(node_schedule, kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1488, in codegen_node_schedule_with_kernel\n    node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCuda.test_foreach_multiple_dynamic_non_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_aot_inductor::AOTInductorTestNonABICompatibleCuda::test_reuse_kernel_dynamic_non_abi_compatible_cuda,gfx90a,"{'message': 'TypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCuda.test_reuse_kernel_dynamic_non_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 1647, in test_reuse_kernel_dynamic\n    self.check_model(m, example_inputs, dynamic_shapes=dynamic_shapes)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor.py"", line 116, in check_model\n    actual = AOTIRunnerUtil.run(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 117, in run\n    so_path = AOTIRunnerUtil.compile(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_aot_inductor_utils.py"", line 63, in compile\n    so_path = torch._inductor.aot_compile(gm, example_inputs, options=options)  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/__init__.py"", line 115, in aot_compile\n    return compile_fx_aot(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1129, in compile_fx_aot\n    compiled_lib_path = compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1239, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1281, in compile_fx\n    return compile_fx(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1500, in compile_fx\n    return inference_compiler(unlifted_gm, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 663, in _compile_fx_inner\n    compiled_graph = codegen_and_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1836, in compile_to_fn\n    code, linemap = self.codegen_with_cpp_wrapper()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1628, in codegen_with_cpp_wrapper\n    compiled = self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py"", line 80, in codegen_node\n    return self._triton_scheduling.codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1174, in codegen_node\n    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1380, in codegen_node_schedule\n    self.codegen_node_schedule_with_kernel(node_schedule, kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1488, in codegen_node_schedule_with_kernel\n    node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 147, in _run_sympy_handler\n    acc = handler(acc, args[i])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_aot_inductor.py AOTInductorTestNonABICompatibleCuda.test_reuse_kernel_dynamic_non_abi_compatible_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::CpuTests::test_dtype_sympy_expr_cpu,gfx90a,"{'message': 'torch._dynamo.exc.BackendCompilerFailed: backend=\'inductor\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py CpuTests.test_dtype_sympy_expr_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1438, in _call_user_compiler\n    compiled_fn = compiler_fn(gm, self.example_inputs())\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py"", line 129, in __call__\n    compiled_gm = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/backends/inductor.py"", line 16, in inductor\n    return compile_fx(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1507, in compile_fx\n    return aot_autograd(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/backends/common.py"", line 72, in __call__\n    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1033, in aot_module_simplified\n    compiled_fn = dispatch_and_compile()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1022, in dispatch_and_compile\n    compiled_fn, _ = create_aot_dispatcher_function(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 435, in create_aot_dispatcher_function\n    return _create_aot_dispatcher_function(flat_fn, flat_args, aot_config)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 736, in _create_aot_dispatcher_function\n    compiled_fn, fw_metadata = compiler_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py"", line 564, in aot_dispatch_autograd\n    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 653, in _compile_fx_inner\n    compiled_graph = FxGraphCache.load(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py"", line 1290, in load\n    compiled_graph = compile_fx_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1854, in compile_to_fn\n    return self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 4115, in codegen_node\n    cpp_kernel_proxy.codegen_nodes(nodes)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3606, in codegen_nodes\n    self.codegen_functions(fn_list, var_sizes_list, vec_dtype)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3416, in codegen_functions\n    scalar_kernel = codegen_kernel(CppKernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3393, in codegen_kernel\n    run(kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3405, in run\n    fn(vars, reduction_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3590, in fn\n    return node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 145, in _run_sympy_handler\n    acc = handler(args[0], args[1])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 8524, in test_dtype_sympy_expr\n    result = fn(torch.randn([1, 2, 16, 4]).requires_grad_())\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py"", line 465, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 1238, in __call__\n    return self._torchdynamo_orig_callable(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 514, in __call__\n    return _compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 902, in _compile\n    guarded_code = compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 653, in compile_inner\n    return _compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_utils_internal.py"", line 85, in wrapper_function\n    return StrobelightCompileTimeProfiler.profile_compile_time(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_strobelight/compile_time_profiler.py"", line 129, in profile_compile_time\n    return func(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 686, in _compile_inner\n    out_code = transform_code_object(code, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py"", line 1322, in transform_code_object\n    transformations(instructions, code_options)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 208, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 622, in transform\n    tracer.run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2731, in run\n    super().run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 958, in run\n    while self.step():\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 870, in step\n    self.dispatch_table[inst.opcode](self, inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2922, in RETURN_VALUE\n    self._return(inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2907, in _return\n    self.output.compile_subgraph(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1109, in compile_subgraph\n    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1361, in compile_and_call_fx_graph\n    compiled_fn = self.call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1408, in call_user_compiler\n    return self._call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1457, in _call_user_compiler\n    raise BackendCompilerFailed(self.compiler_fn, e) from e\ntorch._dynamo.exc.BackendCompilerFailed: backend=\'inductor\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py CpuTests.test_dtype_sympy_expr_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::CpuTests::test_scalar_output_cpu,gfx90a,"{'message': 'torch._dynamo.exc.BackendCompilerFailed: backend=\'compile_fx_wrapper\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py CpuTests.test_scalar_output_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1438, in _call_user_compiler\n    compiled_fn = compiler_fn(gm, self.example_inputs())\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py"", line 129, in __call__\n    compiled_gm = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py"", line 129, in __call__\n    compiled_gm = compiler_fn(gm, example_inputs)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 429, in compile_fx_wrapper\n    return compile_fx(model_, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1507, in compile_fx\n    return aot_autograd(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/backends/common.py"", line 72, in __call__\n    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1033, in aot_module_simplified\n    compiled_fn = dispatch_and_compile()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1022, in dispatch_and_compile\n    compiled_fn, _ = create_aot_dispatcher_function(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 435, in create_aot_dispatcher_function\n    return _create_aot_dispatcher_function(flat_fn, flat_args, aot_config)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 736, in _create_aot_dispatcher_function\n    compiled_fn, fw_metadata = compiler_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py"", line 178, in aot_dispatch_base\n    compiled_fw = compiler(fw_module, updated_flat_args)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 653, in _compile_fx_inner\n    compiled_graph = FxGraphCache.load(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py"", line 1290, in load\n    compiled_graph = compile_fx_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1854, in compile_to_fn\n    return self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 4115, in codegen_node\n    cpp_kernel_proxy.codegen_nodes(nodes)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3606, in codegen_nodes\n    self.codegen_functions(fn_list, var_sizes_list, vec_dtype)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3416, in codegen_functions\n    scalar_kernel = codegen_kernel(CppKernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3393, in codegen_kernel\n    run(kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3405, in run\n    fn(vars, reduction_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3590, in fn\n    return node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 145, in _run_sympy_handler\n    acc = handler(args[0], args[1])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 3369, in test_scalar_output\n    self.common(fn, [arg0_1, arg2_1])\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 437, in check_model\n    actual = run(*example_inputs, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py"", line 465, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 1238, in __call__\n    return self._torchdynamo_orig_callable(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 514, in __call__\n    return _compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 902, in _compile\n    guarded_code = compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 653, in compile_inner\n    return _compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_utils_internal.py"", line 85, in wrapper_function\n    return StrobelightCompileTimeProfiler.profile_compile_time(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_strobelight/compile_time_profiler.py"", line 129, in profile_compile_time\n    return func(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 686, in _compile_inner\n    out_code = transform_code_object(code, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py"", line 1322, in transform_code_object\n    transformations(instructions, code_options)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 208, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 622, in transform\n    tracer.run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2731, in run\n    super().run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 958, in run\n    while self.step():\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 870, in step\n    self.dispatch_table[inst.opcode](self, inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2922, in RETURN_VALUE\n    self._return(inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2907, in _return\n    self.output.compile_subgraph(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1134, in compile_subgraph\n    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1361, in compile_and_call_fx_graph\n    compiled_fn = self.call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1408, in call_user_compiler\n    return self._call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1457, in _call_user_compiler\n    raise BackendCompilerFailed(self.compiler_fn, e) from e\ntorch._dynamo.exc.BackendCompilerFailed: backend=\'compile_fx_wrapper\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py CpuTests.test_scalar_output_cpu\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::GPUTests::test_convolution1_cuda,gfx90a,"{'message': 'AssertionError: Tensor-likes are not close!\n\nMismatched elements: 249 / 2352 (10.6%)\nGreatest absolute difference: 0.00146484375 at index (1, 3, 8, 8) (up to 6e-05 allowed)\nGreatest relative difference: 0.289794921875 at index (1, 3, 11, 6) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution1_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 3993, in test_convolution1\n    self.common(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 622, in check_model_gpu\n    check_model(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 478, in check_model\n    self.assertEqual(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py"", line 3858, in assertEqual\n    raise error_metas.pop()[0].to_error(\nAssertionError: Tensor-likes are not close!\n\nMismatched elements: 249 / 2352 (10.6%)\nGreatest absolute difference: 0.00146484375 at index (1, 3, 8, 8) (up to 6e-05 allowed)\nGreatest relative difference: 0.289794921875 at index (1, 3, 11, 6) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution1_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::GPUTests::test_convolution3_cuda,gfx90a,"{'message': 'AssertionError: Tensor-likes are not close!\n\nMismatched elements: 249 / 2352 (10.6%)\nGreatest absolute difference: 0.00146484375 at index (1, 3, 8, 8) (up to 6e-05 allowed)\nGreatest relative difference: 0.289794921875 at index (1, 3, 11, 6) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution3_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 11286, in new_test\n    return value(self)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 4026, in test_convolution3\n    self.common(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 622, in check_model_gpu\n    check_model(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 478, in check_model\n    self.assertEqual(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py"", line 3858, in assertEqual\n    raise error_metas.pop()[0].to_error(\nAssertionError: Tensor-likes are not close!\n\nMismatched elements: 249 / 2352 (10.6%)\nGreatest absolute difference: 0.00146484375 at index (1, 3, 8, 8) (up to 6e-05 allowed)\nGreatest relative difference: 0.289794921875 at index (1, 3, 11, 6) (up to 0.002 allowed)\n\nThe failure occurred for item [0]\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_convolution3_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::GPUTests::test_dtype_sympy_expr_cuda,gfx90a,"{'message': 'torch._dynamo.exc.BackendCompilerFailed: backend=\'inductor\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_dtype_sympy_expr_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1438, in _call_user_compiler\n    compiled_fn = compiler_fn(gm, self.example_inputs())\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py"", line 129, in __call__\n    compiled_gm = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/backends/inductor.py"", line 16, in inductor\n    return compile_fx(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1507, in compile_fx\n    return aot_autograd(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/backends/common.py"", line 72, in __call__\n    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1033, in aot_module_simplified\n    compiled_fn = dispatch_and_compile()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1022, in dispatch_and_compile\n    compiled_fn, _ = create_aot_dispatcher_function(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 435, in create_aot_dispatcher_function\n    return _create_aot_dispatcher_function(flat_fn, flat_args, aot_config)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 736, in _create_aot_dispatcher_function\n    compiled_fn, fw_metadata = compiler_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py"", line 564, in aot_dispatch_autograd\n    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 653, in _compile_fx_inner\n    compiled_graph = FxGraphCache.load(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py"", line 1290, in load\n    compiled_graph = compile_fx_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1854, in compile_to_fn\n    return self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 4115, in codegen_node\n    cpp_kernel_proxy.codegen_nodes(nodes)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3606, in codegen_nodes\n    self.codegen_functions(fn_list, var_sizes_list, vec_dtype)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3416, in codegen_functions\n    scalar_kernel = codegen_kernel(CppKernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3393, in codegen_kernel\n    run(kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3405, in run\n    fn(vars, reduction_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cpp.py"", line 3590, in fn\n    return node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 145, in _run_sympy_handler\n    acc = handler(args[0], args[1])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 8524, in test_dtype_sympy_expr\n    result = fn(torch.randn([1, 2, 16, 4]).requires_grad_())\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py"", line 465, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 1238, in __call__\n    return self._torchdynamo_orig_callable(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 514, in __call__\n    return _compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 902, in _compile\n    guarded_code = compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 653, in compile_inner\n    return _compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_utils_internal.py"", line 85, in wrapper_function\n    return StrobelightCompileTimeProfiler.profile_compile_time(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_strobelight/compile_time_profiler.py"", line 129, in profile_compile_time\n    return func(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 686, in _compile_inner\n    out_code = transform_code_object(code, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py"", line 1322, in transform_code_object\n    transformations(instructions, code_options)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 208, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 622, in transform\n    tracer.run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2731, in run\n    super().run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 958, in run\n    while self.step():\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 870, in step\n    self.dispatch_table[inst.opcode](self, inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2922, in RETURN_VALUE\n    self._return(inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2907, in _return\n    self.output.compile_subgraph(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1109, in compile_subgraph\n    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1361, in compile_and_call_fx_graph\n    compiled_fn = self.call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1408, in call_user_compiler\n    return self._call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1457, in _call_user_compiler\n    raise BackendCompilerFailed(self.compiler_fn, e) from e\ntorch._dynamo.exc.BackendCompilerFailed: backend=\'inductor\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_dtype_sympy_expr_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
inductor.test_torchinductor::GPUTests::test_scalar_output_cuda,gfx90a,"{'message': 'torch._dynamo.exc.BackendCompilerFailed: backend=\'compile_fx_wrapper\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_scalar_output_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0', 'text': 'Traceback (most recent call last):\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1438, in _call_user_compiler\n    compiled_fn = compiler_fn(gm, self.example_inputs())\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py"", line 129, in __call__\n    compiled_gm = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py"", line 129, in __call__\n    compiled_gm = compiler_fn(gm, example_inputs)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 429, in compile_fx_wrapper\n    return compile_fx(model_, example_inputs_)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1507, in compile_fx\n    return aot_autograd(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/backends/common.py"", line 72, in __call__\n    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1033, in aot_module_simplified\n    compiled_fn = dispatch_and_compile()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 1022, in dispatch_and_compile\n    compiled_fn, _ = create_aot_dispatcher_function(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 435, in create_aot_dispatcher_function\n    return _create_aot_dispatcher_function(flat_fn, flat_args, aot_config)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py"", line 736, in _create_aot_dispatcher_function\n    compiled_fn, fw_metadata = compiler_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py"", line 178, in aot_dispatch_base\n    compiled_fw = compiler(fw_module, updated_flat_args)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1336, in fw_compiler_base\n    return _fw_compiler_base(model, example_inputs, is_inference)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 1407, in _fw_compiler_base\n    return inner_compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 468, in compile_fx_inner\n    return wrap_compiler_debug(_compile_fx_inner, compiler_name=""inductor"")(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py"", line 85, in debug_wrapper\n    inner_compiled_fn = compiler_fn(gm, example_inputs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 653, in _compile_fx_inner\n    compiled_graph = FxGraphCache.load(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codecache.py"", line 1290, in load\n    compiled_graph = compile_fx_fn(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 563, in codegen_and_compile\n    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/compile_fx.py"", line 864, in fx_codegen_and_compile\n    compiled_fn = graph.compile_to_fn()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1854, in compile_to_fn\n    return self.compile_to_module().call\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1780, in compile_to_module\n    return self._compile_to_module()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1786, in _compile_to_module\n    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/graph.py"", line 1725, in codegen\n    self.scheduler.codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3149, in codegen\n    return self._codegen()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 3207, in _codegen\n    self.get_backend(device).codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py"", line 80, in codegen_node\n    return self._triton_scheduling.codegen_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1174, in codegen_node\n    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1380, in codegen_node_schedule\n    self.codegen_node_schedule_with_kernel(node_schedule, kernel)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/simd.py"", line 1488, in codegen_node_schedule_with_kernel\n    node.codegen(index_vars)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/scheduler.py"", line 913, in codegen\n    with V.set_ops_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 119, in __enter__\n    return next(self.gen)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/codegen/common.py"", line 1641, in set_current_node\n    self.node_to_bounds = node._body.bounds().get_bounds()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/utils.py"", line 457, in wrapper\n    setattr(self, key, fn(self))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 74, in get_bounds\n    interpreter.run(V.get_ops_handler(), initial_env=self._bounds)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6678, in run\n    return super().run(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 147, in run\n    self.env[node] = self.run_node(node)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/ir.py"", line 6674, in run_node\n    return super().run_node(n)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 204, in run_node\n    return getattr(self, n.op)(n.target, args, kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/fx/interpreter.py"", line 321, in call_module\n    return submod(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_inductor/bounds.py"", line 135, in get_index\n    bound = bound_sympy(expr, self.replacement_vals)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 1086, in bound_sympy\n    return sympy_interp(SymPyValueRangeAnalysis, ranges, expr)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in sympy_interp\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 183, in <listcomp>\n    [sympy_interp(analysis, env, arg) for arg in expr.args],  # type: ignore[arg-type]\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 181, in sympy_interp\n    return _run_sympy_handler(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/interp.py"", line 145, in _run_sympy_handler\n    acc = handler(args[0], args[1])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 562, in mul\n    return ValueRanges.coordinatewise_monotone_map(a, b, _keep_float(safe_mul))\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_sympy/value_ranges.py"", line 418, in coordinatewise_monotone_map\n    return ValueRanges(min(products), max(products))\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/decorators.py"", line 236, in _func\n    return func(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/expr.py"", line 365, in __lt__\n    return StrictLessThan(self, other)\n  File ""/root/.local/lib/python3.9/site-packages/sympy/core/relational.py"", line 843, in __new__\n    raise TypeError(""Invalid NaN comparison"")\nTypeError: Invalid NaN comparison\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 3369, in test_scalar_output\n    self.common(fn, [arg0_1, arg2_1])\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/contextlib.py"", line 79, in inner\n    return func(*args, **kwds)\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 590, in check_model_gpu\n    check_model(\n  File ""/var/lib/jenkins/pytorch/test/inductor/test_torchinductor.py"", line 437, in check_model\n    actual = run(*example_inputs, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py"", line 465, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 1238, in __call__\n    return self._torchdynamo_orig_callable(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 514, in __call__\n    return _compile(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 902, in _compile\n    guarded_code = compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 653, in compile_inner\n    return _compile_inner(code, one_graph, hooks, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_utils_internal.py"", line 85, in wrapper_function\n    return StrobelightCompileTimeProfiler.profile_compile_time(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_strobelight/compile_time_profiler.py"", line 129, in profile_compile_time\n    return func(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 686, in _compile_inner\n    out_code = transform_code_object(code, transform)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py"", line 1322, in transform_code_object\n    transformations(instructions, code_options)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 208, in _fn\n    return fn(*args, **kwargs)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py"", line 622, in transform\n    tracer.run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2731, in run\n    super().run()\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 958, in run\n    while self.step():\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 870, in step\n    self.dispatch_table[inst.opcode](self, inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2922, in RETURN_VALUE\n    self._return(inst)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py"", line 2907, in _return\n    self.output.compile_subgraph(\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1134, in compile_subgraph\n    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1361, in compile_and_call_fx_graph\n    compiled_fn = self.call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1408, in call_user_compiler\n    return self._call_user_compiler(gm)\n  File ""/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_dynamo/output_graph.py"", line 1457, in _call_user_compiler\n    raise BackendCompilerFailed(self.compiler_fn, e) from e\ntorch._dynamo.exc.BackendCompilerFailed: backend=\'compile_fx_wrapper\' raised:\nTypeError: Invalid NaN comparison\n\nSet TORCH_LOGS=""+dynamo"" and TORCHDYNAMO_VERBOSE=1 for more information\n\n\nYou can suppress this exception and fall back to eager by setting:\n    import torch._dynamo\n    torch._dynamo.config.suppress_errors = True\n\n\nTo execute this test, run the following from the base repo dir:\n    PYTORCH_TEST_WITH_ROCM=1 python test/inductor/test_torchinductor.py GPUTests.test_scalar_output_cuda\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'}",,,ethanwee1
